[phases.setup]
nixPkgs = ["python313", "gcc"]
aptPkgs = ["curl"]
cmds = ["curl -LsSf https://astral.sh/uv/install.sh | sh"]

[phases.install]
cmds = [". $HOME/.local/bin/env && uv sync --no-dev"]

[start]
cmd = ".venv/bin/python main.py"
